version: '3.4'
services:
  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql:5.7.22
    env_file: .env
    volumes:
      - ./mysql/:/var/lib/mysql
    ports:
      - 3306:3306

  osticket:
    container_name: osticket
    restart: unless-stopped
    image: devinsolutions/osticket:latest
    depends_on:
      - mysql
    env_file: .env
    ports:
    - 5335:80