version: '3.4'
services:
  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: osticket
      MYSQL_PASSWORD: secret
      MYSQL_USER: osticket
    volumes:
      - ./mysql/:/var/lib/mysql
    ports:
      - 3306:3306

  osticket:
    container_name: osticket
    restart: unless-stopped
    image: devinsolutions/osticket:latest
    depends_on:
      - mysql
    environment:
      INSTALL_SECRET: secret
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: secret
      CRON_INTERVAL: 1
    ports:
    - 5335:80